spring.application.name=Blog_API
server.port=8081
spring.data.mongodb.uri = mongodb+srv://yurildss:f65N8cPUx9iKCyw4@cluster0.w88hogj.mongodb.net/blogdb?retryWrites=true&w=majority&appName=Cluster0
jwt.secret = YWRhc2RhYTU0ZDZhc2Q3YXNkOGFzOTFkYXM4ZDdh